const crypto = require('crypto');

// Check if Pinata keys are configured
const isPinataConfigured = () => {
  return process.env.PINATA_API_KEY && process.env.PINATA_API_SECRET;
};

/**
 * Generates a mock IPFS CID for a given content string or object.
 * Uses SHA-256 to create a deterministic hash and formats it like a CIDv0 (Qm...).
 */
const generateMockCid = (content) => {
  const contentStr = typeof content === 'string' ? content : JSON.stringify(content);
  const hash = crypto.createHash('sha256').update(contentStr).digest('hex');
  // Simple mock to look like a CIDv0 (Starts with Qm and has 46 chars)
  // We use part of the hex hash and base58-like characters
  const base58chars = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
  let mockCid = 'Qm';
  for (let i = 0; i < 44; i++) {
    const charIndex = parseInt(hash.substring(i, i + 2), 16) % base58chars.length;
    mockCid += base58chars[charIndex];
  }
  return mockCid;
};

/**
 * Pins JSON metadata to IPFS.
 * @param {Object} metadata The JSON metadata object.
 * @returns {Promise<string>} The IPFS URI (ipfs://CID).
 */
const pinJSONToIPFS = async (metadata) => {
  if (isPinataConfigured()) {
    try {
      const response = await fetch('https://api.pinata.cloud/pinning/pinJSONToIPFS', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          pinata_api_key: process.env.PINATA_API_KEY,
          pinata_secret_api_key: process.env.PINATA_API_SECRET,
        },
        body: JSON.stringify({
          pinataContent: metadata,
          pinataMetadata: {
            name: metadata.name ? `Metadata-${metadata.name}` : 'Credify-Metadata'
          }
        }),
      });

      if (!response.ok) {
        throw new Error(`Pinata API error: ${response.statusText}`);
      }

      const data = await response.json();
      return `ipfs://${data.IpfsHash}`;
    } catch (error) {
      console.error('Failed to pin JSON to Pinata, falling back to mock:', error);
    }
  }

  // Fallback or local testing mode
  const mockCid = generateMockCid(metadata);
  return `ipfs://${mockCid}`;
};

/**
 * Pins a file (like an SVG string) to IPFS.
 * @param {string} fileContent The string content of the file.
 * @param {string} fileName The name of the file.
 * @returns {Promise<string>} The IPFS URI (ipfs://CID).
 */
const pinFileToIPFS = async (fileContent, fileName) => {
  if (isPinataConfigured()) {
    try {
      const FormData = require('form-data');
      const formData = new FormData();
      
      // Convert string to buffer for form-data
      const buffer = Buffer.from(fileContent, 'utf-8');
      formData.append('file', buffer, { filename: fileName || 'image.svg' });

      const response = await fetch('https://api.pinata.cloud/pinning/pinFileToIPFS', {
        method: 'POST',
        headers: {
          pinata_api_key: process.env.PINATA_API_KEY,
          pinata_secret_api_key: process.env.PINATA_API_SECRET,
          // Note: When using native fetch with form-data in Node, 
          // we might need to let fetch determine the content-type boundary,
          // or use the headers generated by form-data if using axios.
          ...formData.getHeaders()
        },
        body: formData, // Node 18+ fetch might not perfectly support form-data stream body, might need axios or alternative if issues arise, but for now fallback is fine.
      });

      if (!response.ok) {
        throw new Error(`Pinata API error: ${response.statusText}`);
      }

      const data = await response.json();
      return `ipfs://${data.IpfsHash}`;
    } catch (error) {
      console.error('Failed to pin File to Pinata, falling back to mock:', error);
    }
  }

  // Fallback or local testing mode
  const mockCid = generateMockCid(fileContent);
  return `ipfs://${mockCid}`;
};

module.exports = {
  pinJSONToIPFS,
  pinFileToIPFS
};
